### ISSUE TITLE
Quick & Dirty way to log raw request/response?

### ISSUE THREAD

**Issue by aashanand** [charliebone/shopifyr#3]
Just wondering if you had a preferred way to log the actual request/response sent by Shopify so as to troubleshoot any errors or weird response codes.

For example, if I use getProduct('some_id_here'), I get a list containing the the product's attributes (if the product ID exists). Is there a way to log the raw response from Shopify without using something like the httr package?

**Comment by charliebone** [comment]
Hello, I apologize for the *very* late reply! For future reference, you can log raw requests / responses and CURL output via the verbose parameter. So in your example above, you would use getProduct('some_id_here', verbose=TRUE) and the output of the request and response would be printed to the screen so you could troubleshoot things like status codes.
