### ISSUE TITLE
metafield definition docs?

### ISSUE THREAD

**Issue by Eflores89** [charliebone/shopifyr#4]
Thanks for this! It's coming in really handy... Is there documentation I can see regarding all the metafields? To see what I should add. 

If I download the product template in csv in Shopify, the fields are obviously not the same because they must have an alias. Do you know where I can find docs regarding this?

**Comment by charliebone** [comment]
Hi, apologies for the late reply. The best documentation for metafields that I know of is on the Shopify website via https://help.shopify.com/en/api/reference/metafield. 

Metafields are basically a very loose key/value information store for certain Shopify resources and can be used for many things including the front end of stores via Liquid. So you can basically create your own metafields as you see fit. From what I recall there may also be some built-in metafields as well for some resources but this may no longer be the case.
