### ISSUE TITLE
A way to retrieve orders after a specified date?

### ISSUE THREAD

**Issue by dnmabra12** [charliebone/shopifyr#5]
Thank you for this!!

Is there a way to use getOrders to retrieve orders on or after a specified time interval? It looks like I have to retrieve all orders in a shop before being able to filter out, which for large shops takes too long unfortunately. Is there anyway to retrieve a limited amount of orders by some given condition?

**Comment by charliebone** [comment]
Hello, I am sorry for the late reply. As per the Shopify documentation (see https://help.shopify.com/en/api/reference/orders/order#index), you can filter the requested orders using a few different parameters. So for example if I wanted all orders created on or after June 1st, I could make a call to my ShopifyShop object as follows:

`orders <- shop$getOrders(created_at_min="2019-06-01T00:00:00-06:00")`

As Shopify accepts only ISO-8601 strings, I would recommend using something like the `format_iso_8601` function from the parsedate package (https://cran.r-project.org/web/packages/parsedate/index.html).
