### ISSUE TITLE
Error initializing ShopifyShop instance

### ISSUE THREAD

**Issue by landrumb** [charliebone/shopifyr#6]
When trying to run `store <- ShopifyShop$new(storeURL,storePassword, quiet = FALSE)`, I get the following error:
`Error in .subset2(public_bind_env, "initialize")(...) : 
  Error accessing Shopify :  Curl error : error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

**Comment by charliebone** [comment]
Hi, please try installing the current development version from Github (instructions near the top of the README). The old codebase did not support TLS and has since been updated. I will work to get a new version on CRAN at some point soon but there are a few more things I'd like to do beforehand.
