### ISSUE TITLE
Corrupted shopifyr.rdb

### ISSUE THREAD

**Issue by landrumb** [charliebone/shopifyr#7]
Typing anything into RStudio that is autofilled by a term from shopifyr gives an error saying `~/shopifyr/help/shopifyr.rdb` is corrupt.

Workaround found is to delete the help directory entirely.

This is in most recent commit dae07184b44a1c95622c5f3309ff46987d642b48

**Comment by charliebone** [comment]
Hi, I am unable to reproduce this error. Have you tried removing the entire package and reinstalling cleanly? If it persists in that case can you please provide the output of `sessionInfo()` and any other information you think can help with this?

As the `remotes` package installs from source and I haven't put out any binaries, the rdb is compiled in your R session, so it's possible the package was not compiled properly and simply trying another install may do the trick.
